# Generated by Django 3.0.3 on 2020-02-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default=None, help_text='Enter a brief description of the book', max_length=1000),
            preserve_default=False,
        ),
    ]
